services:
  - type: web
    name: aetherguard-inference-engine-v5
    env: python
    region: ohio
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python backend/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: TEMP_UPLOADS
        value: ./temp_uploads
    healthCheckPath: /api/health
